version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: alex
    versions:
    - "> 8.2.0"
  - dependency-name: husky
    versions:
    - ">= 4.a, < 5"
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: webpack-manifest-plugin
    versions:
    - 3.0.0
    - 3.1.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.6
    - 1.3.7
    - 1.4.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.1
    - 7.13.13
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.0
    - 13.0.1
  - dependency-name: css-loader
    versions:
    - 5.1.2
  - dependency-name: "@babel/eslint-parser"
    versions:
    - 7.13.0
    - 7.13.4
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.2
    - 5.0.0
    - 5.1.0
  - dependency-name: terser-webpack-plugin
    versions:
    - 5.1.1
  - dependency-name: sass-loader
    versions:
    - 11.0.0
    - 11.0.1
