# deployment job templates
# upload ${{SOURCE_PATH}} to azure blob
parameters:
  dependsOn: []
  condition: succeeded()
  NAME: "web_deployment"
  AZURE_SUBSCRIPTION: ""
  STORAGE: "$(STORAGE)" # the storage
  BLOB_PREFIX: "" # the subfolder name
  CONTAINER_NAME: $web # the container name default is $web
  SOURCE_PATH: "$(Agent.BuildDirectory)/drop"
  TEAMS_WEBHOOK: ""
  MESSAGE: ""

jobs:
  - deployment: ${{ parameters.NAME }} # name of the deployment job, A-Z, a-z, 0-9, and underscore
    # friendly name to display in the UI
    # displayName: upload to ${{coalesce(parameters.STORAGE, variables.STORAGE) }}:${{ coalesce(parameters.CONTAINER_NAME,variables.CONTAINER_NAME) }}/${{ parameters.BLOB_PREFIX }}
    pool: # see pool schema
      vmImage: "windows-2019"
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    cancelTimeoutInMinutes: 5 # how much time to give 'run always even if cancelled tasks' before killing them
    environment: azure-static-website-deploy # target environment name and optionally a resource-name to record the deployment history; format: <environment-name>.<resource-name>
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzureFileCopy@3
              displayName: "Copy files to Azure blob"
              inputs:
                azureSubscription: "${{ parameters.AZURE_SUBSCRIPTION }}"
                storage: ${{ parameters.STORAGE }} # ${{ coalesce(, variables.STORAGE) }}
                containerName: ${{ parameters.CONTAINER_NAME }}
                blobPrefix: ${{ parameters.BLOB_PREFIX }}
                sourcePath: "${{ parameters.SOURCE_PATH }}"
                destination: AzureBlob
            - ${{ if and(parameters.TEAMS_WEBHOOK, parameters.MESSAGE) }}:
                - powershell: Invoke-RestMethod -Method post -ContentType 'Application/Json' -Body "$env:MESSAGE_BODY" -Uri ${{parameters.TEAMS_WEBHOOK}}
                  displayName: post messsage to Teams
                  continueOnError: true
                  env:
                    MESSAGE_BODY: '{"text":"${{parameters.MESSAGE}}"}'

            # https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20threads/create?view=azure-devops-rest-6.0
            - powershell: |
                Invoke-RestMethod -Method post -ContentType 'Application/Json' -Body "$env:MESSAGE" -Uri "$env:API" -Headers @{
                  Authorization="Bearer $(System.AccessToken)"
                }
              displayName: Comment PR
              continueOnError: true
              condition: eq(variables['Build.Reason'], 'PullRequest')
              env:
                API: "$(System.CollectionUri)/_apis/git/repositories/$(Build.Repository.ID)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=6.0"
                MESSAGE: '{"comments":[{"parentCommentId":0,"content":"${{parameters.MESSAGE}}","commentType":3}],"status":2}'
