# DG APP Azure Pipelines
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# global variables
variables:
  AZURE_SUBSCRIPTION: "" # https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#use-a-service-connection
  STORAGE: "" # must be lowercase or number
  TEAMS_WEBHOOK: "" # send messages in teams webhook

trigger:
  batch: true # batch changes if true (the default); start a new build for every push if false
  branches:
    include: # branch names which will trigger a build
      - "master"
  paths:
    # include: [web] # file paths which must match to trigger a build
    exclude: [.vscode] # file paths which will not trigger a build

jobs:
  - job: web_build # name of the deployment job, A-Z, a-z, 0-9, and underscore
    displayName: Build ${{variables['Build.SourceBranchName']}} to Static Website # friendly name to display in the UI
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: ./steps/build.yml
        parameters:
          BUILD_ENV: ${{variables['Build.SourceBranchName']}}
          PUBLISH_BUILD: true
          PUBLISH_TEST: true

  - template: ./jobs/deploy-azure.yml
    parameters:
      dependsOn: [web_build]
      NAME: "web_deploy"
      AZURE_SUBSCRIPTION: "${{variables.AZURE_SUBSCRIPTION}}"
      CONTAINER_NAME: $web
      TEAMS_WEBHOOK: ${{variables.TEAMS_WEBHOOK}}
      TEAMS_MESSAGE: |
        **$(Build.Repository.Name) `${{variables['Build.SourceBranchName']}}` deployed!**

        > $(Build.SourceVersionMessage)
        >
        > created by `$(Build.RequestedFor)`
