# global variables
variables:
  AZURE_SUBSCRIPTION: "" # https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#use-a-service-connection
  STORAGE: "" # must be lowercase or number

trigger: none # will disable CI builds entirely
pr:
  autoCancel: true

jobs:
  - job: pr_build # name of the deployment job, A-Z, a-z, 0-9, and underscore
    displayName: Build Pull Request # friendly name to display in the UI
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - template: ./steps/build.yml
        parameters:
          BUILD_ENV: ${{variables['Build.SourceBranchName']}}
      - script: npm run build-storybook --if-present
        displayName: build storybook
      - template: ./steps/publish-results.yml

  # check in Mac/Win/Linux with different node versions to avoid breaking cross platform dev
  - job: compatibility_check
    condition: in(variables['system.pullRequest.targetBranch'], 'refs/heads/master')
    strategy:
      matrix:
        mac:
          node_version: 12.x
          imageName: "macOS-latest"
        windows:
          node_version: 12.x
          imageName: "windows-latest"
        linux_node10:
          node_version: 10.x
          imageName: "ubuntu-latest"
    variables:
      # disable ComponentGovernanceDetection https://docs.opensource.microsoft.com/tools/cg/policyinjection.html
      skipComponentGovernanceDetection: true
    pool:
      vmImage: $(imageName)
    steps:
      - template: ./steps/build.yml
        parameters:
          BUILD_ENV: "production"
          NODE_VERSION: $(node_version)
          CACHE_KEY: '"$(node_version)" | "node_modules" | "$(Agent.OS)" | package-lock.json'

  - template: ./jobs/deploy-azure.yml
    parameters:
      NAME: "pr_test_deploy"
      dependsOn: [pr_build, compatibility_check]
      AZURE_SUBSCRIPTION: "${{variables.AZURE_SUBSCRIPTION}}"
      CONTAINER_NAME: build
      BLOB_PREFIX: $(Build.BuildID)
      TEAMS_WEBHOOK: ${{variables.TEAMS_WEBHOOK}}
      MESSAGE: |
        **[$(Build.Repository.Name) PR#$(System.PullRequest.PullRequestId)]($(System.PullRequest.SourceRepositoryURI)/pullrequest/$(System.PullRequest.PullRequestId)) build Success!**
        > $(Build.SourceVersionMessage)
        >
        > created by `$(Build.RequestedFor)`.
        Following is the preview URL
        **[https://$(STORAGE)--build--$(Build.BuildID).dg-app.com/](https://$(STORAGE)--build--$(Build.BuildID).dg-app.com/)**
