name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: yarn
      - name: Alex
        run: yarn alex
      - name: test-format
        run: yarn test-format
